/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utry_javaCallDLL_AlgorithmDLL */


#ifndef _Included_com_utry_javaCallDLL_AlgorithmDLL
#define _Included_com_utry_javaCallDLL_AlgorithmDLL

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utry_javaCallDLL_AlgorithmDLL
 * Method:    ini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_utry_javaCallDLL_AlgorithmDLL_ini(JNIEnv *, jclass);


/*
* Class:     com_utry_javaCallDLL_AlgorithmDLL
* Method:    DPM
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT jfloatArray JNICALL Java_com_utry_javaCallDLL_AlgorithmDLL_DPM(JNIEnv *, jobject, jstring, jstring);


/*
* Class:     com_utry_javaCallDLL_AlgorithmDLL
* Method:    DPMbool
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT jint JNICALL Java_com_utry_javaCallDLL_AlgorithmDLL_DPMbool(JNIEnv *, jobject, jstring, jstring);



/*
* Class:     com_utry_javaCallDLL_AlgorithmDLL
* Method:    DPMvector
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT std::vector<FLOATS_7>  JNICALL Java_com_utry_javaCallDLL_AlgorithmDLL_DPMvector(JNIEnv *, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
